spring:
  application:
    name: remote-config
  cloud:
    config:
      username: admin
      password: s3cr3tpa55word
      label: v1
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888


management:
  endpoints:
    web:
      exposure:
        include: refresh

# app properties
app:
  message: Hello from App, new day!